<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TelkatBhaat" failures="0" tests="1" name="com.haullog.haullog.controllers.expenseControllerTests.addExpenseControllerTests.AddExpenseControllerSuccessTest" time="1.637" errors="1" timestamp="2024-05-08T00:59:38 GMT-07:00" skipped="0">
  <testcase classname="com.haullog.haullog.controllers.expenseControllerTests.addExpenseControllerTests.AddExpenseControllerSuccessTest" name="testAddExpenseControllerSuccess" time="1.637">
    <error message="Cannot invoke &quot;com.haullog.haullog.models.Expense.getExpenseId()&quot; because &quot;savedExpense&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.haullog.haullog.models.Expense.getExpenseId()" because "savedExpense" is null
at com.haullog.haullog.controllers.ExpenseController.addExpense(ExpenseController.java:33)
at com.haullog.haullog.controllers.expenseControllerTests.addExpenseControllerTests.AddExpenseControllerSuccessTest.testAddExpenseControllerSuccess(AddExpenseControllerSuccessTest.java:47)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- testAddExpenseControllerSuccess -->
</testsuite> <!-- com.haullog.haullog.controllers.expenseControllerTests.addExpenseControllerTests.AddExpenseControllerSuccessTest -->
